package database

type migration struct {
	Version int
	SQLite  []string
	MySQL   []string
}

var migrations = []migration{
	{
		Version: 1,
		SQLite: []string{
			`CREATE TABLE users (
				singleton_key INTEGER PRIMARY KEY CHECK (singleton_key = 1),
				id TEXT NOT NULL UNIQUE,
				username TEXT NOT NULL,
				normalized_username TEXT NOT NULL UNIQUE,
				password_hash TEXT NOT NULL,
				initialized_at TEXT NOT NULL,
				created_at TEXT NOT NULL,
				updated_at TEXT NOT NULL,
				last_login_at TEXT
			)`,
			`CREATE TABLE sessions (
				token_hash BLOB PRIMARY KEY CHECK (length(token_hash) = 32),
				csrf_hash BLOB NOT NULL CHECK (length(csrf_hash) = 32),
				user_id TEXT NOT NULL,
				expires_at TEXT NOT NULL,
				absolute_expires_at TEXT NOT NULL,
				last_seen_at TEXT NOT NULL,
				created_at TEXT NOT NULL,
				FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
			)`,
			`CREATE INDEX sessions_user_id_idx ON sessions(user_id)`,
			`CREATE INDEX sessions_expires_at_idx ON sessions(expires_at)`,
		},
		MySQL: []string{
			`CREATE TABLE users (
				singleton_key TINYINT NOT NULL PRIMARY KEY,
				id VARCHAR(36) NOT NULL UNIQUE,
				username VARCHAR(255) NOT NULL,
				normalized_username VARCHAR(255) NOT NULL UNIQUE,
				password_hash VARCHAR(1024) NOT NULL,
				initialized_at DATETIME(6) NOT NULL,
				created_at DATETIME(6) NOT NULL,
				updated_at DATETIME(6) NOT NULL,
				last_login_at DATETIME(6) NULL,
				CONSTRAINT users_singleton_check CHECK (singleton_key = 1)
			) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
			`CREATE TABLE sessions (
				token_hash BINARY(32) NOT NULL PRIMARY KEY,
				csrf_hash BINARY(32) NOT NULL,
				user_id VARCHAR(36) NOT NULL,
				expires_at DATETIME(6) NOT NULL,
				absolute_expires_at DATETIME(6) NOT NULL,
				last_seen_at DATETIME(6) NOT NULL,
				created_at DATETIME(6) NOT NULL,
				INDEX sessions_user_id_idx (user_id),
				INDEX sessions_expires_at_idx (expires_at),
				CONSTRAINT sessions_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
			) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
		},
	},
	{
		Version: 2,
		SQLite: []string{
			`CREATE TABLE provider_connections (
				id TEXT PRIMARY KEY,
				name TEXT NOT NULL,
				provider_type TEXT NOT NULL,
				endpoint TEXT NOT NULL DEFAULT '',
				settings_json TEXT NOT NULL,
				credentials_ciphertext BLOB NOT NULL,
				credentials_nonce BLOB NOT NULL,
				credentials_key_version INTEGER NOT NULL CHECK (credentials_key_version > 0),
				enabled INTEGER NOT NULL CHECK (enabled IN (0, 1)),
				health_status TEXT NOT NULL,
				last_tested_at TEXT,
				last_synced_at TEXT,
				last_error_code TEXT NOT NULL DEFAULT '',
				last_error_message TEXT NOT NULL DEFAULT '',
				created_at TEXT NOT NULL,
				updated_at TEXT NOT NULL,
				deleted_at TEXT
			)`,
			`CREATE INDEX provider_connections_type_idx ON provider_connections(provider_type)`,
			`CREATE INDEX provider_connections_active_idx ON provider_connections(deleted_at, enabled)`,
			`CREATE TABLE servers (
				id TEXT PRIMARY KEY,
				connection_id TEXT NOT NULL,
				external_id TEXT NOT NULL,
				scope TEXT NOT NULL DEFAULT '',
				name TEXT NOT NULL,
				normalized_state TEXT NOT NULL,
				remote_state TEXT NOT NULL,
				spec_json TEXT NOT NULL,
				addresses_json TEXT NOT NULL,
				capabilities_json TEXT NOT NULL,
				portal_url TEXT,
				last_seen_at TEXT NOT NULL,
				last_state_checked_at TEXT NOT NULL,
				hidden_at TEXT,
				created_at TEXT NOT NULL,
				updated_at TEXT NOT NULL,
				FOREIGN KEY (connection_id) REFERENCES provider_connections(id) ON DELETE RESTRICT,
				UNIQUE (connection_id, scope, external_id)
			)`,
			`CREATE INDEX servers_visible_idx ON servers(hidden_at, normalized_state, name)`,
			`CREATE INDEX servers_connection_idx ON servers(connection_id, hidden_at)`,
			`CREATE TABLE jobs (
				id TEXT PRIMARY KEY,
				kind TEXT NOT NULL,
				payload_json TEXT NOT NULL,
				status TEXT NOT NULL,
				attempts INTEGER NOT NULL DEFAULT 0,
				max_attempts INTEGER NOT NULL,
				available_at TEXT NOT NULL,
				lease_owner TEXT,
				lease_expires_at TEXT,
				last_error TEXT NOT NULL DEFAULT '',
				created_at TEXT NOT NULL,
				updated_at TEXT NOT NULL
			)`,
			`CREATE INDEX jobs_available_idx ON jobs(status, available_at)`,
			`CREATE INDEX jobs_lease_idx ON jobs(status, lease_expires_at)`,
		},
		MySQL: []string{
			`CREATE TABLE provider_connections (
				id VARCHAR(36) NOT NULL PRIMARY KEY,
				name VARCHAR(255) NOT NULL,
				provider_type VARCHAR(64) NOT NULL,
				endpoint VARCHAR(2048) NOT NULL DEFAULT '',
				settings_json LONGTEXT NOT NULL,
				credentials_ciphertext LONGBLOB NOT NULL,
				credentials_nonce VARBINARY(32) NOT NULL,
				credentials_key_version INT NOT NULL,
				enabled BOOLEAN NOT NULL,
				health_status VARCHAR(32) NOT NULL,
				last_tested_at DATETIME(6) NULL,
				last_synced_at DATETIME(6) NULL,
				last_error_code VARCHAR(128) NOT NULL DEFAULT '',
				last_error_message TEXT NOT NULL,
				created_at DATETIME(6) NOT NULL,
				updated_at DATETIME(6) NOT NULL,
				deleted_at DATETIME(6) NULL,
				INDEX provider_connections_type_idx (provider_type),
				INDEX provider_connections_active_idx (deleted_at, enabled),
				CONSTRAINT provider_connections_key_version_check CHECK (credentials_key_version > 0)
			) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
			`CREATE TABLE servers (
				id VARCHAR(36) NOT NULL PRIMARY KEY,
				connection_id VARCHAR(36) NOT NULL,
				external_id VARCHAR(255) NOT NULL,
				scope VARCHAR(255) NOT NULL DEFAULT '',
				name VARCHAR(255) NOT NULL,
				normalized_state VARCHAR(32) NOT NULL,
				remote_state VARCHAR(255) NOT NULL,
				spec_json LONGTEXT NOT NULL,
				addresses_json LONGTEXT NOT NULL,
				capabilities_json LONGTEXT NOT NULL,
				portal_url VARCHAR(2048) NULL,
				last_seen_at DATETIME(6) NOT NULL,
				last_state_checked_at DATETIME(6) NOT NULL,
				hidden_at DATETIME(6) NULL,
				created_at DATETIME(6) NOT NULL,
				updated_at DATETIME(6) NOT NULL,
				UNIQUE KEY servers_remote_unique (connection_id, scope, external_id),
				INDEX servers_visible_idx (hidden_at, normalized_state, name),
				INDEX servers_connection_idx (connection_id, hidden_at),
				CONSTRAINT servers_connection_fk FOREIGN KEY (connection_id) REFERENCES provider_connections(id) ON DELETE RESTRICT
			) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
			`CREATE TABLE jobs (
				id VARCHAR(36) NOT NULL PRIMARY KEY,
				kind VARCHAR(64) NOT NULL,
				payload_json LONGTEXT NOT NULL,
				status VARCHAR(32) NOT NULL,
				attempts INT NOT NULL DEFAULT 0,
				max_attempts INT NOT NULL,
				available_at DATETIME(6) NOT NULL,
				lease_owner VARCHAR(255) NULL,
				lease_expires_at DATETIME(6) NULL,
				last_error TEXT NOT NULL,
				created_at DATETIME(6) NOT NULL,
				updated_at DATETIME(6) NOT NULL,
				INDEX jobs_available_idx (status, available_at),
				INDEX jobs_lease_idx (status, lease_expires_at)
			) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
		},
	},
}
